version: "2"

services:
  mongo:
    restart: always
    image: mongo:4.0.2
    container_name: mongo
    volumes:
      - $DATA/DatabseFiles:/data/db

  # reverse-proxy:
  #   restart: always
  #   image: raminarmanfar/reverse-proxy
  #   container_name: reverse-proxy
  #   ports:
  #     - $EXPOSE_PORT:80
  #     - 443:443
  #   depends_on:
  #     - backend-app
  #     - mongo-express
  #   links:
  #     - backend-app
  #     - mongo-express

  backend-app:
    restart: always
    image: raminarmanfar/backend-cloud-app:1.0.0
    container_name: backend-app
    depends_on:
      - mongo
    environment:
      - HTTP_PORT=5000
      - MONGODB_URL=mongo
      - MONGODB_PORT=27017
      - MONGODB_NAME=$MONGODB_NAME
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PW=$MONGODB_PW

  frontend-app:
    restart: always
    image: raminarmanfar/frontend-cloud-app:1.0.0
    container_name: frontend-app
    depends_on:
      - backend-app
    command: ['nginx', '-g', 'daemon off;']
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy.conf:/etc/nginx/proxy.conf
    ports:
      - 80:80
